select * from [hshjohannesh10].[hshjohannesh10].[ru_users]
select * from [hshjohannesh10].[hshjohannesh10].[ru_drivers]
select * from [hshjohannesh10].[hshjohannesh10].[ru_trips]
select * from [hshjohannesh10].[hshjohannesh10].[ru_driver_ratings]
select * from [hshjohannesh10].[hshjohannesh10].[ru_products]